apiVersion: v1
kind: Secret
metadata:
  name: auto-kubernetes-lets-encrypt-certs
type: Opaque
# Create an empty secret (with no data) in order for the update to work
---
apiVersion: batch/v1
kind: Job
metadata:
  name: auto-kubernetes-lets-encrypt
  labels:
    app: auto-kubernetes-lets-encrypt
spec:
  template:
    metadata:
      name: auto-kubernetes-lets-encrypt
      labels:
        app: auto-kubernetes-lets-encrypt
    spec:
      containers:
      - image: quay.io/hiphipjorge/auto-kubernetes-lets-encrypt:latest
        name: auto-kubernetes-lets-encrypt
        imagePullPolicy: Always
        ports:
        - name: main
          containerPort: 80
        env:
        - name: DOMAINS
          value: go-test.jorge.fail
        - name: EMAIL
          value: jorge.silva@thejsj.com
        - name: SECRET
          value: auto-kubernetes-lets-encrypt-certs
      restartPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: auto-kubernetes-lets-encrypt
spec:
  selector:
    app: auto-kubernetes-lets-encrypt
  ports:
  - protocol: "TCP"
    port: 80
